###
POST http://localhost:4444/api/users HTTP/1.1
Content-Type: application/json

{
    "name":"Denisse Mondragon",
    "age": "15",
    "email": "Dyussess@gmail.com"
}



###
GET http://localhost:4444/api/users HTTP/1.1


###
GET http://localhost:4444/api/users/624297c72e1287cb6d70a537 HTTP/1.1

###
PUT  http://localhost:4444/api/users/62429d899e5644a0a6fcd809 HTTP/1.1
Content-Type: application/json

{
    "name":"Miguel Paniagua",
    "age": "64",
    "email": "pintor77@gmail.com"
}

###
DELETE  http://localhost:4444/api/users/62429f92df902a5c51687fe8 HTTP/1.1


